version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    container_name: spacenote-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL:-}  # Optional email for Let's Encrypt
    volumes:
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
    entrypoint: /bin/sh
    command: >
      -c "echo '
      {
        email ${EMAIL:-}
      }

      ${DOMAIN} {
        reverse_proxy /api/* backend:8000
        reverse_proxy frontend:80
      }
      ' | caddy run --config /dev/stdin --adapter caddyfile"
    networks:
      - spacenote-network

  mongodb:
    image: mongodb/mongodb-community-server:8.2-ubi9
    container_name: spacenote-mongodb
    restart: unless-stopped
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGODB_INITDB_DATABASE: spacenote
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - spacenote-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: ${BACKEND_IMAGE:-spacenote-backend:latest}
    container_name: spacenote-backend
    restart: unless-stopped
    environment:
      SPACENOTE_DATABASE_URL: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@mongodb:27017/spacenote?authSource=admin
      SPACENOTE_SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      SPACENOTE_CORS_ORIGINS: '["https://${DOMAIN}"]'
      SPACENOTE_HOST: 0.0.0.0
      SPACENOTE_PORT: 8000
      SPACENOTE_DEBUG: ${DEBUG:-false}
    depends_on:
      - mongodb
    networks:
      - spacenote-network

  frontend:
    image: ${FRONTEND_IMAGE:-spacenote-frontend:latest}
    container_name: spacenote-frontend
    restart: unless-stopped
    environment:
      API_URL: https://${DOMAIN}
    depends_on:
      - backend
    networks:
      - spacenote-network

networks:
  spacenote-network:
    driver: bridge